# -*- coding: utf-8 -*-
"""Değişkenler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FInMINIQlZEtWzeYlP8vxo2Hiz6JIoZN
"""

liste1=3
print('Değişkenin içindeki sayı: ', liste1)
liste1='Müjgan'
print('Değişkenin içindeki değer: ', liste1)
liste1=10.5
print('Değişkenin içindeki sayı: ', liste1)
#Değişkenin veri tipi değer atandığında tanımlandığı için aynı değişkene hem sayısal hem de karakter dizisi atanabilir.

a=b=c=1
print('1.sayı=', a)
print('2.sayı=', b)
print('3.sayı=', c)
#Değişkene hem string ifade hem sayısal değerler atanabilir.

adi, soyadi, yasi='Müjgan', 'Şahin', '19'
print("Adı=", adi)
print("Soyadı=", soyadi)
print("Yaşı=", yasi)
#Değişkenler aralarına virgül eklenerek yan yana yazılır.

adi='Müjgan' ; soyadi='Şahin' ; yasi='19'
print("Adı=", adi)
print("Soyadı=", soyadi)
print("Yaşı=", yasi)
#Değişken-değer ikilileri arasına noktalı virgül eklenerek de yan yana yazılır.

print(yeni_liste)
#Değişkene değer atanmadığı için hata mesajı verir.

yeni_liste=int()
print(yeni_liste)
#Bu uygulama yapılması durumunda değişkene tanımlanan ilk değer 0 olur.

sayi=7
metin='python'
print(sayi+metin)
#Bir sayı ile bir kelimeyi toplayamayız.Değişkenler veri tiplerine uygun kullanılmalı.

import keyword
keyword.kwlist

#Büyük harf ve küçük harf kullanılarak tanımlanan değişkenlerin adı aynı olsa bile farklı değişkenlerdir.
sayi1=1
Sayi1=2
print(sayi1)
print(Sayi1)

sayı1=3
print(sayı1)
#Değişken adlandırmada Türkçe karakterler kullanılabilir.

1sayi=5
print(1sayi)
#Hatalı değişken adı.Sayıyla başlanamaz.

#Camel standartlarında değişken tanımlama
adi="Müjgan"
soyadi="Şahin"
yaşi=19
dogumYili=2004
universiteMezunuMu=False
bölümü="Havacılık ve uzay mühendisliği"
print("Adı: ", adi)
print("Soyadı: ", soyadi)
print("Yaşı: ", yaşi)
print("Doğum Yılı: ", dogumYili)
print("Üniversite mezunu mu? ", universiteMezunuMu)
print("Bölümü: ", bölümü)