# -*- coding: utf-8 -*-
"""part1_örnekler.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-W4Jv7E-8nwe2OCFK50PxqnmTGAxqSc
"""

# Veliye öğrencisinin devamsızlığını bildiren mesaj metni yazan kodları yazınız. Veli adını soyadını, 
# mesajın içeriğini, devamsızlık süresini ayrı değişkenlere atayarak aşağıdaki gibi bir mesajda yazdırın. 
# Sn..... .......öğrencinizin toplam devamsızlığı .... gündür. 

önMesaj='Sayın '
veliAd='Ege '
veliSoyad='Koç '
mesajMetni1='öğrencinizin toplam devamsızlığı: '
devamsızlık='7.5 '
mesajMetni2='gündür. İyi günler dileriz. MMBAL'
mesaj=önMesaj+veliAd+veliSoyad+mesajMetni1+devamsızlık+mesajMetni2
print(mesaj)

#Tüketiciye su faturasını bildiren mesaj metni oluşturan kodları yazınız.
#Kullanıcıya fatura tutarını belirten mesajda kullanılacak değişkenler: Hitap şekli, abone numarası, 
#tüketim dönemi, tüketim tutarı*1.
#Sayın ...nolu abonemiz .................. dönemi faturanız ...... TL’dir. 

önMesaj="Sayın "
sonMesaj="Temmuz 2023 dönemi faturanız: "
aboneNo="1234567"
tüketim="100"
tutar=int(tüketim)*1.0
mesaj=önMesaj+str(aboneNo)+' nolu abonemiz '+sonMesaj+ str(tutar)+" TL'dir. Konyaaltı Belediyesi"
print(mesaj)