# -*- coding: utf-8 -*-
"""veri_tipleri.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXfZgIhZTE-tBlJtkOMBArlwz7UBelr_
"""

sayi1=7
sayi2='3'
print(sayi1+sayi2)
#Kod hata uyarısı verir.Değişkenin tek tırnak içinde olup olmaması ve karakter dizisi olmasına dikkat edilmelidir.
#Bir karakter dizisi ile bir sayı toplanmaya çalışıldığında hata mesajı verir.

sayi1=7
sayi2='3'
print(sayi1*sayi2)

piSayisi=3.14 #Float
print("Pi sayısı= ",piSayisi)
yariçap=3 #İnteger
print("Yarıçap= ",yariçap)
alan=3.14*3*3 #Float
print("Alan= ",alan)
karmaşikSayi=2+7j #Complex
print("Bir karmaşık sayi= ",karmaşikSayi)

metin1="Merhaba"
metin2="Dünya"
print(metin1) #İlgili karakter dizisinin tamamını yazdırır.
print(metin1*2) #Karakter dizisini 2 kez yazdırır.
print(metin1+metin2) #İki karakter dizisini birleştirir.
print("metin1 değişkenindeki değerin uzunluğu= ",len(metin1)) #len() metodubir karakter dizisinin uzunluğunu verir.
#Boşluk da bir karakterdir.

metin="Merhaba Dünya"
print(metin[0]) #İlk karakteri yazar.
print(metin[4:7]) #İfadenin 5,6 ve 7. karakterlerini yazar.
print(metin[8::]) #9. karakterden sonuncu karaktere kadar yazar.
print(metin[-1]) #En sondaki ifadeyi yazar.
print(metin[:7]) #İndisi 0 dan 7 ye kadar olan karakterleri yazar.
print(metin[8:]) #8.indisten sonraki tüm karakterleri yazar.
print(metin[0:8:2]) #0,2,4 ve 6 indis numaralı karakterleri yazar.

sayi1=7
sayi2=12.34567
metin1="1881"
sayi3=5+2j
askerlikYaptiMi=True #True doğru,1,evet anlamındadır.
print("1. değişkenin veri tipi: ", type(sayi1))
print("2. değişkenin veri tipi: ", type(sayi2))
print("3. değişkenin veri tipi: ", type(metin1))
print("4. değişkenin veri tipi: ", type(sayi3))
print("5. değişkenin veri tipi: ", type(askerlikYaptiMi))

listem=['Müjgan',19,'Mühendis',True]
print("6. değişkenin veri tipi: ",type(listem))
demet1=('Müjgan',19,'Mühendis',True)
print("7. değişkenin veri tipi: ",type(demet1))
sozluk={'adi': 'Müjgan','soyadi': 'Şahin','yaşi':19,'mesleği':'mühendis'}
print("8. değişkenin veri tipi: ",type(sozluk))
#Bir değişkenin veri tipi type() komutuyla kontrol edilir.

metin1='7'
metin2='3'
print(metin1+metin2)
#Tırnak içinde girilen değerler karakter dizisi kabul edilir.

print(int(metin1)+int(metin2))
#Sayısal değerlere çevirmek için integer a çevirmemiz gerekir.

piSayisi=3.14
print('Veri Tipi: ',type(piSayisi))
yariçap=3
daireAlani=((piSayisi*2)*yariçap)
print('Dairenin alanı float değer: ',daireAlani)
pideğeri=(int(piSayisi))
print('Yeni veri tipi:',type(pideğeri))
daireAlaniİnt=((pideğeri*2)*yariçap)
print('Dairenin Alanı int değer: ',daireAlaniİnt)

askerlikYaptiMi=True
print('Askerlik yaptı mı?', askerlikYaptiMi)
askerlikYaptiMiİnt=int(askerlikYaptiMi) #integer tipine dönüştü.
print('Askerlik yaptı mı?', askerlikYaptiMiİnt)
askerlikYaptiMiStr=str(askerlikYaptiMi) #string tipine dönüştü.
print('Askerlik yaptı mı?', askerlikYaptiMiStr) #Çıktı olarak true verse de tipi stringtir.