# -*- coding: utf-8 -*-
"""yorum_satırları.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KmvRKBAPzHQB4EISNoKJaeAXlnUPEL1M
"""

print("Merhaba Dünya")

#Yorum satırları kullanılarak bir hatırlatma eklenebilir.
#Kodlarla ilgili açıklama yapılabilir.
#Aktif olan bir kod satırını pasif duruma getirmek için kullanılabilir.
print("Yorum satırlarını kullanmayı öğreniyoruz.")
#print("Bugünün konusu yorum satırları.")

print(2+3) #Bu kod satırı ekrana 2 sayının toplamını yazdırır.
#Aynı satırda hem kod satırı hem yorum satırı kullanabiliriz.
#Kod çalışırken ilk öndeki kod çalışır yorum satırı dikkate alınmaz.

'''Birden çok yorum satırı
kullanmak için baş ve sondaki satırlara 
üçlü tek tırnak veya çift tırnak
kullanılabilir.'''

#!/usr/bin/env python3 veya #!c:/Python/python.exe
# -*- coding: utf-8 -*-
"#!/usr/bin/env python3" #kodu Python 3 yorumlayıcısının Linux için dosya konumunu belirtir.
"#!c:/Python/python.exe" #kodu Python 3 yorumlayıcısının Windows için dosya konumunu bildirir.
"# -*- coding: utf-8 -*- " #Kullanacağınız karakter kodlamasını belirtmek için kullanılır.utf-8 Türkçe alfabeyi de destekleyen bir karakter kodlama sistemidir.

#Yorum satırları süsleme amacıyla da kullanabilir.
'''
# # # # # # # # # # # # # # # 
#  *  *  *  *  *  *  *  *   #
#  *       Python       *   #
#  *                    *   #
#  *  *  *  *  *  *  *  *   #
# # # # # # # # # # # # # # #
'''